### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by puttpotsawee** [anilanar/moxios#19]
Try to run it in Node.js and got this error

```shell
/Users/user/product-name/project/application/node_modules/@anilanar/moxios/dist/webpack:/moxios/webpack/universalModuleDefinition:10
})(window, function(__WEBPACK_EXTERNAL_MODULE_axios__, __WEBPACK_EXTERNAL_MODULE_axios_lib_core_createError__, __WEBPACK_EXTERNAL_MODULE_axios_lib_core_settle__, __WEBPACK_EXTERNAL_MODULE_axios_lib_helpers_btoa__, __WEBPACK_EXTERNAL_MODULE_axios_lib_helpers_buildURL__, __WEBPACK_EXTERNAL_MODULE_axios_lib_helpers_cookies__, __WEBPACK_EXTERNAL_MODULE_axios_lib_helpers_isURLSameOrigin__) {
 ^
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/user/product-name/project/application/node_modules/@anilanar/moxios/dist/webpack:/moxios/webpack/universalModuleDefinition:10:2)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/product-name/project/application/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/product-name/project/application/test/api/transunion.test.js:9:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/user/product-name/project/application/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/product-name/project/application/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/user/product-name/project/application/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/user/product-name/project/application/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/user/product-name/project/application/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/user/product-name/project/application/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

**Comment by anilanar** [comment]
Thanks for reporting, fixed in version `0.9.0`.
